export const SET_UPDATES = "SET_UPDATES";
export const SET_LOADING = "SET_LOADING";
export const SET_TOKEN = "SET_TOKEN";
export const SET_AUTH = "SET_AUTH";
export const LOGOUT = "LOGOUT";

export const COMMON_FETCH_AUTH_BY_PASSWORD = "COMMON_FETCH_AUTH_BY_PASSWORD";
export const COMMON_FETCH_AUTH_BY_TOKEN = "COMMON_FETCH_AUTH_BY_TOKEN";
export const COMMON_FETCH_LOGOUT = "COMMON_FETCH_LOGOUT";
export const COMMON_FETCH_PENDING = "COMMON_FETCH_PENDING";
export const COMMON_FETCH_FAILED = "COMMON_FETCH_FAILED";
export const COMMON_FETCH_AUTH_SUCCEEDED = "COMMON_FETCH_AUTH_SUCCEEDED";
export const COMMON_FETCH_LOGOUT_SUCCEEDED = "COMMON_FETCH_LOGOUT_SUCCEEDED";
