export const MAZE_FETCH_DATA = 'MAZE_FETCH_DATA';
export const MAZE_FETCH_PENDING = 'MAZE_FETCH_PENDING';
export const MAZE_FETCH_SUCCEEDED = 'MAZE_FETCH_SUCCEEDED';
export const MAZE_FETCH_FAILED = 'MAZE_FETCH_FAILED';
