export const UPDATES_FETCH_DATA = "UPDATES_FETCH_DATA";
export const UPDATES_FETCH_PENDING = "UPDATES_FETCH_PENDING";
export const UPDATES_FETCH_SUCCEEDED = "UPDATES_FETCH_SUCCEEDED";
export const UPDATES_FETCH_FAILED = "UPDATES_FETCH_FAILED";
