export const USERS_FETCH_DATA = "USERS_FETCH_DATA";
export const USERS_FETCH_DATA_PENDING = "USERS_FETCH_DATA_PENDING";
export const USERS_FETCH_DATA_SUCCSEEDED = "USERS_FETCH_DATA_SUCCSEEDED";
export const USERS_FETCH_DATA_FAILED = "USERS_FETCH_DATA_FAILED";
export const USERS_ADD_USER = "USERS_ADD_USER";
export const USERS_ADD_USER_SUCCEEDED = "USERS_ADD_USER_SUCCEEDED";
