export const USER_FETCH_DATA = "USER_FETCH_DATA";
export const USER_FETCH_DATA_PENDING = "USER_FETCH_DATA_PENDING";
export const USER_FETCH_DATA_FAILED = "USER_FETCH_DATA_FAILED";
export const USER_FETCH_DATA_SUCCSEEDED = "USER_FETCH_DATA_SUCCSEEDED";
export const USER_ON_PATH_LEAVE = "USER_ON_PATH_LEAVE";

export const USER_EDIT_PROPS = "USER_EDIT_PROPS";
export const USER_ADD_PLAYER = "USER_ADD_PLAYER";
export const USER_DELETE_PLAYER = "USER_DELETE_PLAYER";
export const USER_RESET_PLAYER = "USER_RESET_PLAYER";
