export const SET_USERS_DATA = "SET_USERS";
export const SET_USER_DATA = "SET_USER";

export const USERS_FETCH_DATA = "USERS_FETCH_DATA";
export const USERS_FETCH_DATA_PENDING = "USERS_FETCH_DATA_PENDING";
export const USERS_FETCH_DATA_SUCCSEEDED = "USERS_FETCH_DATA_SUCCSEEDED";
export const USERS_FETCH_DATA_FAILED = "USERS_FETCH_DATA_FAILED";
